title:         "Bulma-Extensions"
description:   "Set of missing Bulma.io functionalities provided as SASS / JavaScript extensions."
env:           "production"

# Build

markdown:      kramdown
permalink:     pretty
url:           https://wikiki.github.io
exclude:       ['node_modules/bulma/CHANGELOG.md', 'bulma-docs.sass', 'package.json']
sass:
  load_paths:
      - _sass
      - node_modules
  style:       compressed

# Icons

fontawesome:   https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css
iconic:        https://cdnjs.cloudflare.com/ajax/libs/open-iconic/1.1.1/font/css/open-iconic.min.css
ionicons:      https://code.ionicframework.com/ionicons/2.0.1/css/ionicons.min.css
mdi:           https://cdn.materialdesignicons.com/2.0.46/css/materialdesignicons.min.css

# Variables

github:        https://github.com/wikiki/bulma-extensions
version:       6.2.4
